enum MeasurementType {
  CONNECTIONS,
  NETWORK_BYTES_IN,
  NETWORK_BYTES_OUT,
  NETWORK_NUM_REQUESTS,
  OPCOUNTER_CMD,
  OPCOUNTER_QUERY,
  OPCOUNTER_UPDATE,
  OPCOUNTER_DELETE,
  OPCOUNTER_GETMORE,
  OPCOUNTER_INSERT,
  LOGICAL_SIZE
}
